<?php if ($iType == 1) {?>
<?php $iTopNav=2; include APP_PATH . '/View/Index/Acenter/topnav.phtml';?>
<?php } else {?>
<?php $iTopNav=1; include APP_PATH . '/View/Index/Mcenter/topnav.phtml';?>
<?php }?>
<div class="cf2 gray_border box_w">
	<dl class="gray_th">
		<dd>推广详情</dd>
	</dl>

	<form autocomplete="off">
	<input type="hidden" name="iAdID" value="<?php echo $aAd['iAdID']?>">
	<table class="fill_table">
		<!--<tr>
			<th width="120px">
				<?php echo $aAd['iMediaType']==Model_Media::TYPE_WEIXIN?'广告位置':'投放形式'?>：
			</th>
			<td>
				<ul class="input_list">
					<li>
						<label>
							<div class="sel_box sel_box_r mediatype">
								<input type="radio" id="mpos-<?php echo $k?>" value="<?php echo $aSetting['iAdPos']?>" name="iAdPos" checked />
								<label for="mpos-<?php echo $aSetting['iAdPos']?>"></label>
							</div>
							<?php echo $aTitle[$aSetting['iAdPos']]?>
						</label>
					</li>
				</ul>
			</td>
		</tr>
		<tr>
			<th>
				投放时间：
			</th>
			<td>
			    <?php echo date('Y-m-d H:i',$aSetting['iPlanTime']);?>
			</td>
		</tr>-->
        <?php include 'ad_' . $aAd['iMediaType'] . '.phtml';?>
	</table>
	
	<table class="list_table">
		<thead>
			<tr>
				<th>订单号</th>
				<th>推广名称</th>
				<th>媒体类型</th>
				<th>执行帐号</th>
				<th>任务时间</th>
				<th>推广金额</th>
				<th>订单状态</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($aList as $k => $v) {?>
			<tr>
				<td>
					<span class="eng"><?php echo $v['iAutoID']?></span>
				</td>
				<td>
					<a target="_blank" class="pinka" href="/index/index/ad/id/<?php echo $v['iAdID']?>/type/2.html"><?php echo $v['aAd']['sAdName']?></a>
				</td>
				<td>
					<span class="eng"><?php echo $aType[$v['aMedia']['iMediaType']]?></span>
				</td>
				<td>
					<span class="eng"><?php echo $v['aAd']['sAdName']?></span>
				</td>
				<td>
					<span class="eng"><?php echo date('Y-m-d H:i', $v['iPlanTime'])?></span>
				</td>
				<td>
					<span class="red_text eng">&yen;<?php echo $v['iMoney']?></span>
				</td>
				<td>
					<span class="eng"><?php echo $aStatus[$v['iStatus']]?></span>
				</td>
			</tr>
		<?php }?>
		</tbody>
	</table>
	</form>
</div>