<div class="pheader clearfix">微信列表</div>
<div class="pbody clearfix">
	<form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/crawlweixin/list.html">
        <div class="row sousuo_now">
            <div class="form-group">
                <label>帐号：</label>
    		    <input type="text" value="<?php echo isset($aParam['sAccount']) ? $aParam['sAccount'] : '' ?>" class="form-control" name="sAccount" style="width: 200px">
        	</div>
        	<div class="form-group">
                <label>公众号：</label>
    		    <input type="text" value="<?php echo isset($aParam['sName']) ? $aParam['sName'] : '' ?>" class="form-control" name="sName" style="width: 200px">
        	</div>
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索">
            </div>
        </div>
    </form>
    <hr>
    <div class="btn-toolbar list-toolbar">
    	<!-- <button class="btn btn-primary" id="crawlweixin_add">
    		<i class="icon-plus"></i> 增加微信
    	</button> -->
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center">帐号</th>
    			<th class="text-center">公众号</th>
    			<th class="text-center">阅读数</th>
    			<th class="text-center">发布次数</th>
    			<th class="text-center">发布篇数</th>
    			<th class="text-center">最高阅读数</th>
    			<th class="text-center">平均阅读数</th>
    			<th class="text-center">总点赞数</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $v) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $v['iWeixinID']?></td>
    			<td class="text-center"><?php echo $v['sAccount']?></td>
    			<td class="text-center"><?php echo $v['sName']?></td>
    			<td class="text-center"><?php echo $v['iReadTotal']?></td>
    			<td class="text-center"><?php echo $v['iPublishTimes']?></td>
    			<td class="text-center"><?php echo $v['iPublishTotal']?></td>
    			<td class="text-center"><?php echo $v['iReadMax']?></td>
    			<td class="text-center"><?php echo $v['iReadAvg']?></td>
    			<td class="text-center"><?php echo $v['iPraiseTotal']?></td>
    			<td class="text-center">
    			    <a href="/admin/crawlweixin/edit?id=<?php echo $v['iWeixinID']?>" title="编辑"><i class="icon-pencil icon-large"></i></a>
    			    <a href="/admin/crawlwxarticle/list?iWeixinID=<?php echo $v['iWeixinID']?>" title="查看"><i class="icon-list icon-large"></i></a>
    			    <!-- <a class="crawlweixin_delete" href="/admin/crawlweixin/del?id=<?php echo $v['iWeixinID']?>" role="button" data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a> -->
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>
<script>
$('.crawlweixin_delete').click(function() {
	if (confirm("您确认要删除该微信吗？")) {
		$.get(this.href, function(ret){
			alert(ret.data);
		    if (ret.status) {
			    location.reload();
		    }
		}, 'json');
	}
	return false;
});
$('#crawlweixin_add').click(function(){
	location.href = '/admin/crawlweixin/add';
});
</script>