<div class="pheader clearfix"><?php echo isset($aMedia['iMediaID'])?'编辑':'增加'?>自媒体</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iMediaID" type="hidden" value="<?php echo isset($aMedia['iMediaID'])?$aMedia['iMediaID']:''?>">
        <?php if(isset($aMedia['iMediaID'])){ ?>
        <div class="form-group">
			<label for="sEmail" class="col-sm-2 control-label"> 归属账号：</label>
			<div class="col-sm-10">
				<?php echo $aUser['sEmail']; ?>
			</div>
		</div>
		<?php } ?>
		<?php if(isset($aMedia['iMediaID'])){ ?>
		<div class="form-group">
			<label for="iMediaType" class="col-sm-2 control-label"> 账号类型：</label>
			<div class="col-sm-10">
				<?php echo $MediaType[$aMedia['iMediaType']]; ?>
			</div>
		</div>
		<?php }else{ ?>
		<input name="iMediaID" type="hidden" value="<?php echo $iMediaType; ?>">
		<?php } ?>
		<div class="form-group">
			<label for="sMediaName" class="col-sm-2 control-label"><strong style="color:red;">*</strong>账号名称：</label>
			<div class="col-sm-10">
				<input name="sMediaName" validate="!length:2-20" type="text" value="<?php echo isset($aMedia['sMediaName'])?$aMedia['sMediaName']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sOpenName" class="col-sm-2 control-label"><strong style="color:red;">*</strong>
				<?php if($MediaType[$aMedia['iMediaType']]=='微信公众号')
				{
					echo '公众号名：'  ;
				}
				else
				{
					echo '微博链接：'  ;
				}  ?> </label>
			<div class="col-sm-10">
			    <input name="sOpenName" validate="!length:2-50" type="text" value="<?php if(isset($aMedia['sOpenName'])&&$MediaType[$aMedia['iMediaType']]=='微信公众号'){
					echo    $aMedia['sOpenName'];
				}
			else if(isset($aMedia['sOpenName'])&&$MediaType[$aMedia['iMediaType']]=='新浪微博'){
			   echo  $aMedia['sUrl'] ;
			}
				?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iFollowerNum" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 粉丝数量：</label>
			<div class="col-sm-10">
			    <input name="iFollowerNum" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iFollowerNum'])?$aMedia['iFollowerNum']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sFollowerImg" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 粉丝认证截图：</label>
			<div class="col-sm-10">
				<input type="hidden" id="sFollowerImg" name="sFollowerImg" value="<?php echo isset($aMedia['sFollowerImg'])?$aMedia['sFollowerImg']:''?>">
				<img id="sFollowerImgShow" style="width:120px;height:90px;" src="<?php echo isset($aMedia['sFollowerImg'])?Util_Uri::getDFSViewURL($aMedia['sFollowerImg'], 130, 130):''?>">
				<input type="button" value="选择" class="plupload" data-target="#sFollowerImg" data-img="#sFollowerImgShow">
			</div>
		</div>
		<div class="form-group">
			<label for="sAvatar" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 头像：</label>
			<div class="col-sm-10">
				<input type="hidden" id="sAvatarImg" name="sAvatar" value="<?php echo isset($aMedia['sAvatar'])?$aMedia['sAvatar']:''?>">
				<img id="sAvatarShow" style="width:120px;height:90px;" src="<?php echo isset($aMedia['sAvatar'])?Util_Uri::getDFSViewURL($aMedia['sAvatar'], 130, 130):''?>">
				<input type="button" value="选择" class="plupload" data-target="#sAvatarImg" data-img="#sAvatarShow">
			</div>
		</div>
		<div class="form-group">
			<label for="sQRCode" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 二维码：</label>
			<div class="col-sm-10">
				<input type="hidden" id="sQRCodeImg" name="sQRCode" value="<?php echo isset($aMedia['sQRCode'])?$aMedia['sQRCode']:''?>">
				<img id="sQRCodeShow" style="width:120px;height:90px;" src="<?php echo isset($aMedia['sQRCode'])?Util_Uri::getDFSViewURL($aMedia['sQRCode'], 130, 130):''?>">
				<input type="button" value="选择" class="plupload" data-target="#sQRCodeImg" data-img="#sQRCodeShow">
			</div>
		</div>
		<div class="form-group">
			<label for="iSoftPrice" class="col-sm-2 control-label"><strong style="color:red;">*</strong>单图文零售价：</label>
			<div class="col-sm-10">
			    <input name="iPrice5" style="width: 300px" validate="!float:true" type="text" value="<?php echo isset($aMedia['iPrice5'])?$aMedia['iPrice5']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
				<span style="position: relative;top: 5px;">用户单图文报价：<?php echo isset($aMedia['iPrice1'])?$aMedia['iPrice1']:''?>元</span>
			</div>
		</div>
		<div class="form-group">
			<label for="iHardPrice" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 多图文第1条零售价：</label>
			<div class="col-sm-10">
			    <input name="iPrice6" validate="!float:true" type="text" value="<?php echo isset($aMedia['iPrice6'])?$aMedia['iPrice6']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
				<span style="position: relative;top: 5px;">用户多图文第一条报价：<?php echo isset($aMedia['iPrice2'])?$aMedia['iPrice2']:''?>元</span>
			</div>
		</div>
		<div class="form-group">
			<label for="iHardPrice" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 多图文第2条零售价：</label>
			<div class="col-sm-10">
			    <input name="iPrice7" validate="!float:true" type="text" value="<?php echo isset($aMedia['iPrice7'])?$aMedia['iPrice7']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
				<span style="position: relative;top: 5px;">用户多图文第二条报价：<?php echo isset($aMedia['iPrice3'])?$aMedia['iPrice3']:''?>元</span>
			</div>
		</div>
		<div class="form-group">
			<label for="iHardPrice" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 多图文第3~N条零售价：</label>
			<div class="col-sm-10">
			    <input name="iPrice8" style="width: 300px"  validate="!float:true" type="text" value="<?php echo isset($aMedia['iPrice8'])?$aMedia['iPrice8']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
				<span style="position: relative;top: 5px;">用户多图文第3~N条报价：<?php echo isset($aMedia['iPrice4'])?$aMedia['iPrice4']:''?>元</span>
			</div>
		</div>
		<div class="form-group">
			<label for="iReadNum" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 阅读量：</label>
			<div class="col-sm-10">
			    <input name="iReadNum" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iReadNum'])?$aMedia['iReadNum']:''?>" style="width: 300px" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iRecommendLevel" class="col-sm-2 control-label"> 推荐级别：</label>
			<div class="col-sm-10">
				<input name="iRecommendLevel" style="width: 300px" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iRecommendLevel'])?$aMedia['iRecommendLevel']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iPersonCharge" class="col-sm-2 control-label"> 负责人：</label>
			<div class="col-sm-10">
				<select name="iPersonCharge" class="form-control" style="width:250px;">
					<option value="0" <?php echo !isset($aMedia['iPersonCharge'])||$aMedia['iPersonCharge']==0?'selected':''?>>请选择</option>
    		    <?php foreach ($adminData as $k => $v) {?>
    		        <option value="<?php echo $v['iAdminID']?>" <?php echo isset($aMedia['iPersonCharge'])&&$aMedia['iPersonCharge']==$v['iAdminID']?'selected':''?>><?php echo $v['sAdminName']?></option>
    		    <?php }?>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iAuditperson" class="col-sm-2 control-label"> 审核人：</label>
			<div class="col-sm-10">
				<select name="iAuditperson" class="form-control" style="width:250px;">
					<option value="0" <?php echo !isset($aMedia['iAuditperson'])||$aMedia['iAuditperson']==0?'selected':''?>>请选择</option>
    		    <?php foreach ($adminData as $k => $v) {?>
    		        <option value="<?php echo $v['iAdminID']?>" <?php echo isset($aMedia['iAuditperson'])&&$aMedia['iAuditperson']==$v['iAdminID']?'selected':''?>><?php echo $v['sAdminName']?></option>
    		    <?php }?>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iAttribute" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 属性：</label>
			<div class="col-sm-10">
			   <select name="iAttribute" class="form-control" style="width:250px;">
    		    <?php foreach ($aAttribute as $k => $v) {?>
    		        <option value="<?php echo $k?>" <?php echo isset($aMedia['iAttribute'])&&$aMedia['iAttribute']==$k?'selected':''?>><?php echo $v?></option>
    		    <?php }?>
    		    </select>
			</div>
		</div>
		<div class="form-group">
			<label for="sWxLink" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 微信链接：</label>
			<div class="col-sm-10">
			    <input name="sWxLink" style="width: 300px" validate="url:true" type="text" value="<?php echo isset($aMedia['sWxLink'])?$aMedia['sWxLink']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iVerifyState" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 认证状态：</label>
			<div class="col-sm-10">
			    <select name="iVerifyState" class="form-control" style="width:250px;">
			    	<?php foreach ($aVerifyState as $k => $v) {?>
    		        	<option value="<?php echo $k?>" <?php echo isset($aMedia['iVerifyState'])&&$aMedia['iVerifyState']==$k?'selected':''?>><?php echo $v?></option>
    		    	<?php }?>
    		    </select>
			</div>
		</div>
    	<div class="form-group">
    		<label for="sCertifiedText" class="col-sm-2 control-label"> 认证信息介绍：</label>
    		<div class="col-sm-10">
    			<textarea name="sCertifiedText" style="width: 300px" class="form-control input-validate" rows="3" cols="20"><?php echo isset($aMedia['sCertifiedText'])?$aMedia['sCertifiedText']:''?></textarea>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sIntroduction" class="col-sm-2 control-label"> 简介：</label>
    		<div class="col-sm-10">
    			<textarea name="sIntroduction" style="width: 300px" class="form-control input-validate" rows="3" cols="20"><?php echo isset($aMedia['sIntroduction'])?$aMedia['sIntroduction']:''?></textarea>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sTagID" class="col-sm-2 control-label"> 标签：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aTag)){ $n = 1; foreach ($aTag as $k => $v) {?>
    		        <input type="checkbox" class="checkbox-inline" name="sTagID[]" value="<?php echo $k?>" <?php echo isset($aMedia['iTagID'])&&in_array($k,$aMedia['iTagID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sCategoryID" class="col-sm-2 control-label"> 资源所属类目：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aTypeInfo)){ $n = 1; foreach ($aTypeInfo as $k => $v) {?>
    		        <input type="checkbox" class="checkbox-inline" name="sCategoryID[]" value="<?php echo $k?>" <?php echo isset($aMedia['aCategoryID'])&&in_array($k,$aMedia['aCategoryID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sCooperateLevelInfo" class="col-sm-2 control-label"> 合作等级：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aCooperateLevel)){ $n = 1; foreach ($aCooperateLevel as $k => $v) {?>
    		        <input type="checkbox" class="checkbox-inline" name="sCooperateLevelInfo[]" value="<?php echo $k?>" <?php echo isset($aMedia['aCooperateLevelInfo'])&&in_array($k,$aMedia['aCooperateLevelInfo'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sCricleID" class="col-sm-2 control-label"> 行业圈子：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aIndustryCircle)){ $n = 1; foreach ($aIndustryCircle as $k => $v) {?>
    		        <input type="checkbox" class="checkbox-inline" name="sCricleID[]" value="<?php echo $k?>" <?php echo isset($aMedia['aCricleID'])&&in_array($k,$aMedia['aCricleID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="sCityID" class="col-sm-2 control-label"> 粉丝覆盖区域：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aCity)){ $n = 1; foreach ($aCity as $k => $v) {?>
    		        <input type="checkbox" class="checkbox-inline" name="sCityID[]" value="<?php echo $k?>" <?php echo isset($aMedia['aCityID'])&&in_array($k,$aMedia['aCityID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
		<div class="form-group">
			<label for="iClickNumber" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 点击量：</label>
			<div class="col-sm-10">
			    <input name="iClickNumber" style="width: 300px" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iClickNumber'])?$aMedia['iClickNumber']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iChoiceNumber" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 选择执行量：</label>
			<div class="col-sm-10">
			    <input name="iChoiceNumber" style="width: 300px" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iChoiceNumber'])?$aMedia['iChoiceNumber']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iArticleNumber" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 文章发布量：</label>
			<div class="col-sm-10">
			    <input name="iArticleNumber" style="width: 300px" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iArticleNumber'])?$aMedia['iArticleNumber']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iZambiaNumber" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 文章点赞量：</label>
			<div class="col-sm-10">
			    <input name="iZambiaNumber" style="width: 300px" validate="!digit:true" type="text" value="<?php echo isset($aMedia['iZambiaNumber'])?$aMedia['iZambiaNumber']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
    	<div class="form-group">
			<label for="iStatus" class="col-sm-2 control-label"> 推荐置顶：</label>
			<div class="col-sm-10">
				<select name="iRecommend" class="form-control" style="width:250px;">
					<option value="<?php echo isset($aMedia['iRecommend']) && $aMedia['iRecommend'] > 0 ? $aMedia['iRecommend'] : '2'; ?>" <?php echo isset($aMedia['iRecommend'])&&$aMedia['iRecommend'] > 0?'selected':''?>>是</option>
					<option value="1" <?php echo isset($aMedia['iRecommend'])&&$aMedia['iRecommend']=='0'?'selected':''?>>否</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="sWxLink" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 利率百分百：</label>
			<div class="col-sm-10">
				<input name="iRate" style="width: 300px"  type="text" value="<?php echo isset($aMedia['iRate'])?$aMedia['iRate']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iStatus" class="col-sm-2 control-label"> 上下架状态：</label>
			<div class="col-sm-10">
				<select name="iPut" class="form-control" style="width:250px;">
					<option value="2" <?php echo isset($aMedia['iPut'])&&$aMedia['iPut']=='2'?'selected':''?>>下架</option>
					<option value="1" <?php echo isset($aMedia['iPut'])&&$aMedia['iPut']=='1'?'selected':''?>>上架</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="iStatus" class="col-sm-2 control-label"> 状态：</label>
			<div class="col-sm-10">
				<select name="iStatus" id="status" class="form-control" style="width:250px;">
					<option value="1" <?php echo isset($aMedia['iStatus'])&&$aMedia['iStatus']=='1'?'selected':''?>>已审核</option>
					<option value="2" <?php echo isset($aMedia['iStatus'])&&$aMedia['iStatus']=='2'?'selected':''?>>未审核</option>
					<option value="3" <?php echo isset($aMedia['iStatus'])&&$aMedia['iStatus']=='3'?'selected':''?>>未通过审核</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="iStatus" class="col-sm-2 control-label"> 审核不通过原因：</label>
			<div class="col-sm-10">
				<textarea name="iExplain" id="explains" disabled class="form-control input-validate" rows="3" cols="20"><?php echo isset($aMedia['iExplain'])?$aMedia['iExplain']:''?></textarea>
			</div>
		</div>
    	<?php if(isset($aMedia['iMediaID'])){ ?>
    	<?php if(isset($aMedia['iUpdateTime']) && $aMedia['iUpdateTime'] > 0){ ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 更新时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aMedia['iUpdateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 创建时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aMedia['iCreateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/media/list/';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	        history.back();
	        }
	    }, 'json');
		return false;
	}});
	$('#status').change(function () {
		if($('#status').val()=='3'){
			$('#explains').attr('disabled',false);
		}
	})
});
</script>
<script type="text/javascript">
global.sUploadUrl = '<?php echo Util_Common::getConf('upload', 'url')?>';
global.sDfsViewUrl = '<?php echo Util_Common::getConf('dfsview', 'url')?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/zh_CN.js"></script>