<div class="pheader clearfix">财务列表</div>
<div class="pbody clearfix">
	<form class="form-inline search-form" role="form" method="post" id="myform" action="">
		<input name="iUserID" type="hidden" value="<?php echo isset($aParam['iUserID'])?$aParam['iUserID']:''?>">
		<input name="iSource" type="hidden" value="4">
        <div class="row sousuo_now">
            <div class="form-group">
                <label>用户名称：</label>
    		    <input type="text" value="<?php echo isset($aParam['sUserRealName']) ? $aParam['sUserRealName'] : '' ?>" class="form-control" name="sUserRealName" style="width: 200px">
        	</div>
           <div class="form-group">
                <label>收支情况：</label>
    		    <select name="iPayment" class="form-control">
    		        <option value="">全部</option>
    		        <option value="1" <?php echo isset($aParam['iPayment'])&&$aParam['iPayment']=='1'?'selected':''?>>收入</option>
    		        <option value="2" <?php echo isset($aParam['iPayment'])&&$aParam['iPayment']=='2'?'selected':''?>>支出</option>
    		    </select>
        	</div>
        	<div class="form-group">
                <label>申请人：</label>
    		    <input type="text" value="<?php echo isset($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>" class="form-control" name="sRealName" style="width: 200px">
        	</div>
           <div class="form-group">
                <label>支付类型：</label>
    		    <select name="iPayType" class="form-control">
    		        <option value="">全部</option>
    		        <option value="1" <?php echo isset($aParam['iPayType'])&&$aParam['iPayType']=='1'?'selected':''?>>支付宝</option>
    		        <option value="2" <?php echo isset($aParam['iPayType'])&&$aParam['iPayType']=='2'?'selected':''?>>微信</option>
    		        <option value="3" <?php echo isset($aParam['iPayType'])&&$aParam['iPayType']=='3'?'selected':''?>>银行卡</option>
    		    </select>
        	</div>
           <div class="form-group">
                <label>支付状态：</label>
    		    <select name="iPayStatus" class="form-control">
    		        <option value="">全部</option>
    		        <option value="0" <?php echo isset($aParam['iPayStatus'])&&$aParam['iPayStatus']=='0'?'selected':''?>>未支付</option>
    		        <option value="1" <?php echo isset($aParam['iPayStatus'])&&$aParam['iPayStatus']=='1'?'selected':''?>>已支付</option>
    		    </select>
        	</div>
            <div class="form-group">
                <!-- <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索"> -->
                <button class="btn btn-default btn-sm" id="formquerybtn">搜索</button>
                <button class="btn btn-default btn-sm" id="formexplodebtn">导出</button>
            </div>
        </div>
    </form>
    <hr>
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="finances_yes">
    		<i class="icon-plus"></i> 已提现
    	</button>
    	<button class="btn btn-primary" id="finances_no">
    		<i class="icon-plus"></i> 未提现
    	</button>
    </div>
    <div class="btn-toolbar list-toolbar">
    	<!-- <button class="btn btn-primary" id="finance_add">
    		<i class="icon-plus"></i> 增加财务
    	</button> -->
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center">用户名称</th>
    			<th class="text-center">收支情况</th>
    			<th class="text-center">事件来源</th>
    			<th class="text-center">申请人</th>
    			<th class="text-center">支付类型</th>
    			<th class="text-center">本次金额</th>
    			<th class="text-center">用户余额</th>
    			<th class="text-center">更新时间</th>
    			<th class="text-center">创建时间</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php
        foreach ($aList['aList'] as $v) {
			$sRealName = isset($aData[$v['iUserID']]['sRealName']) ? $aData[$v['iUserID']]['sRealName'] : '';
			$iPayment = (($v['iPayment'] == '1') ? '收入' : '支出');
			$iSource = '';
			if ($val['iSource'] == '1') {
				$iSource = '自主充值';
			} elseif ($val['iSource'] == '2') {
				$iSource = '付款充值';
			} elseif ($val['iSource'] == '3') {
				$iSource = '拒单退款';
			} elseif ($val['iSource'] == '4') {
				$iSource = '取现';
			} elseif ($val['iSource'] == '5') {
				$iSource = '广告费用';
			}
			$iPayType = '';
			if ($val['iPayType'] == '0') {
				$iPayType = '无';
			} elseif ($val['iPayType'] == '1') {
				$iPayType = '支付宝';
			} elseif ($val['iPayType'] == '2') {
				$iPayType = '微信';
			} elseif ($val['iPayType'] == '3') {
				$iPayType = '银行卡';
			}
        ?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $v['iAutoID']?></td>
    			<td class="text-center"><?php echo $sRealName?></td>
    			<td class="text-center"><?php echo $iPayment;?></td>
    			<td class="text-center"><?php echo $iSource;?></td>
    			<td class="text-center"><?php echo $v['sRealName']?></td>
    			<td class="text-center"><?php echo $iPayType;?></td>
    			<td class="text-center"><?php echo $v['iPayMoney']?></td>
    			<td class="text-center"><?php echo $v['iUserMoney']?></td>
    			<td class="text-center"><?php echo ((isset($v['iUpdateTime']) && $v['iUpdateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iUpdateTime'])) : '');?></td>
    			<td class="text-center"><?php echo ((isset($v['iCreateTime']) && $v['iCreateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iCreateTime'])) : '');?></td>
    			<td class="text-center">
    			    <a href="/admin/finances/edit?id=<?php echo $v['iAutoID']?>" title="编辑"><i class="icon-pencil icon-large"></i></a>
    			    <!-- <a class="finance_delete" href="/admin/finances/del?id=<?php echo $v['iAutoID']?>" role="button" data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a> -->
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>

<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/xcConfirm.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/js/xcConfirm.css"/>
<style type="text/css">
.sgBtn{width: 135px; height: 35px; line-height: 35px; margin-left: 10px; margin-top: 10px; text-align: center; background-color: #0095D9; color: #FFFFFF; float: left; border-radius: 5px;}
</style>
<script>
$('.finance_delete').click(function() {
	var url = this.href;
	if (confirm("您确认要删除该财务吗？")) {
		var txt=  "请输入密码：";
		window.wxc.xcConfirm(txt, window.wxc.xcConfirm.typeEnum.input,{
			onOk:function(v){
				if (v.trim() != '') {
					$.post('/admin/user/seditpwd', {'pwd':v.trim()}, function(ret){
						if (ret.status) {
							$.get(url, function(ret){
								alert(ret.data);
								if (ret.status) {
									location.reload();
								}
							}, 'json');
						}
						else {
							alert(ret.data);
						}
					}, 'json');
				}
				else {
					alert('修改密码不可以为空');
					//return false;
				}
			}
		});
	}
	return false;
});
$("#formquerybtn").bind("click", function() {  
    var url = "/admin/finances/list.html";  
    //更改form的action  
    $("#myform").attr("action", url);  
    //触发submit事件，提交表单   
    $("#myform").submit();  
});
$("#formexplodebtn").bind("click", function() {  
    var url = "/admin/finances/explode.html";  
    //更改form的action  
    $("#myform").attr("action", url);  
    //触发submit事件，提交表单   
    $("#myform").submit();  
});

$('#finance_add').click(function(){
	location.href = '/admin/finances/add';
});
$('#finances_yes').click(function(){
	location.href = '/admin/finances/list?iPayStatus=1';
});
$('#finances_no').click(function(){
	location.href = '/admin/finances/list?iPayStatus=0';
});
</script>