<div class="pheader clearfix"><?php
	echo isset($aAd['iAdID'])?'编辑':'增加'?>广告</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iAdID" type="hidden" value="<?php echo isset($aAd['iAdID'])?$aAd['iAdID']:''?>">
        <input name="iUserID" type="hidden" value="<?php echo isset($aAd['iUserID'])?$aAd['iUserID']:''?>">
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 用户名称：</label>
			<div class="col-sm-10">
				<?php echo $aUser['sRealName']; ?>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 广告名称：</label>
			<div class="col-sm-10">
				<input name="sAdName" disabled type="text" value="<?php echo isset($aAd['sAdName'])?$aAd['sAdName']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 最小投放预算：</label>
			<div class="col-sm-10">
				<input name="iPlanMinMoney" disabled type="text" value="<?php echo isset($aAd['iPlanMinMoney'])?$aAd['iPlanMinMoney']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 最大投放预算：</label>
			<div class="col-sm-10">
				<input name="iPlanMaxMoney" disabled type="text" value="<?php echo isset($aAd['iPlanMaxMoney'])?$aAd['iPlanMaxMoney']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 投放时间：</label>
			<div class="col-sm-10">
				<input type="text" name="iPlanTime" disabled placeholder="选择日期和时间" class="fill_text date_text hover_input datetimepicker form-control input-validate" value="<?php echo ((isset($aAd['iPlanTime']) && $aAd['iPlanTime'] > 0 )?date('Y-m-d H:i',$aAd['iPlanTime']):'');?>" />
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 媒体类型：</label>
			<div class="col-sm-10">
				<select name="iMediaType" disabled class="form-control" style="width:250px;">
    				<option value="1" <?php echo isset($aAd['iMediaType'])&&$aAd['iMediaType']=='1'?'selected':''?>>公众号</option>
    		        <option value="2" <?php echo isset($aAd['iMediaType'])&&$aAd['iMediaType']=='2'?'selected':''?>>朋友圈</option>
    		        <option value="3" <?php echo isset($aAd['iMediaType'])&&$aAd['iMediaType']=='3'?'selected':''?>>新浪微博</option>
    		        <option value="4" <?php echo isset($aAd['iMediaType'])&&$aAd['iMediaType']=='4'?'selected':''?>>新闻论坛</option>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
		</div><div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 广告类型：</label>
			<div class="col-sm-10">
				<select name="iAdType" disabled class="form-control" style="width:250px;">
    				<option value="1" <?php echo isset($aAd['iAdType'])&&$aAd['iAdType']=='1'?'selected':''?>>硬广</option>
    		        <option value="2" <?php echo isset($aAd['iAdType'])&&$aAd['iAdType']=='2'?'selected':''?> selected>软广</option>
    		        <option value="3" <?php echo isset($aAd['iAdType'])&&$aAd['iAdType']=='3'?'selected':''?>>全选</option>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
    		<label for="sTagID" class="col-sm-2 control-label"> 媒体分类：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aCategory)){ $n = 1; foreach ($aCategory as $k => $v) {?>
    		        <input type="checkbox" disabled class="checkbox-inline" name="sCatID[]" value="<?php echo $k?>" <?php echo isset($aAd['sCatID'])&&in_array($k,$aAd['sCatID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
		<div class="form-group">
    		<label for="sTagID" class="col-sm-2 control-label"> 所在城市：</label>
    		<div class="col-sm-10">
    		    <div class="col-sm-8" validate="">
    		    <?php if(isset($aCity)){ $n = 1; foreach ($aCity as $k => $v) {?>
    		        <input type="checkbox" disabled class="checkbox-inline" name="sCityID[]" value="<?php echo $k?>" <?php echo isset($aAd['sCityID'])&&in_array($k,$aAd['sCityID'])?'checked':''?>> <?php echo $v?>
    		    <?php if ($n++ % 8 == 0){echo '<br>';}}}?>
		        </div>
				<span class="validate_checktip"></span>
    		</div>
    	</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 订单总金额：</label>
			<div class="col-sm-10">
				<input name="iMoney" disabled type="text" value="<?php echo isset($aAd['iTotalMoney'])?$aAd['iTotalMoney']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 支付类型：</label>
			<div class="col-sm-10">
				<select name="iPayStatus" disabled class="form-control" style="width:250px;">
    				<option value="0" <?php echo isset($aAd['iPayStatus'])&&$aAd['iPayStatus']=='0'?'selected':''?>>未付款</option>
    		        <option value="1" <?php echo isset($aAd['iPayStatus'])&&$aAd['iPayStatus']=='1'?'selected':''?>>已付款</option>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 状态：</label>
			<div class="col-sm-10">
				<select name="iStatus" disabled class="form-control" style="width:250px;">
    				<option value="1" <?php echo isset($aAd['iStatus'])&&$aAd['iStatus']=='1'?'selected':''?>>待审核</option>
    		        <option value="2" <?php echo isset($aAd['iStatus'])&&$aAd['iStatus']=='2'?'selected':''?>>审核通过</option>
    		        <option value="3" <?php echo isset($aAd['iStatus'])&&$aAd['iStatus']=='3'?'selected':''?>>审核未通过</option>
    		        <option value="4" <?php echo isset($aAd['iStatus'])&&$aAd['iStatus']=='4'?'selected':''?>>完成</option>
    		        <option value="5" <?php echo isset($aAd['iStatus'])&&$aAd['iStatus']=='4'?'selected':''?>>未填写完成</option>
    		    </select>
				<span class="validate_checktip"></span>
			</div>
			<div class="form-group">
				<label for="iStatus" class="col-sm-2 control-label"> 审核不通过原因：</label>
				<div class="col-sm-10">
					<textarea name="iExplain" id="explain" disabled class="form-control input-validate" rows="3" cols="20"><?php echo isset($aAd['iExplain'])?$aAd['iExplain']:''?></textarea>
				</div>
			</div>
		</div>
		<?php if(isset($aAd['iAdID'])){ ?>
    	<?php if(isset($aAd['iUpdateTime']) && $aAd['iUpdateTime'] > 0){ ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 更新时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aAd['iUpdateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 创建时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aAd['iCreateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
<!--    	<div class="btn-toolbar text-center">-->
<!--        	<button id="save" class="btn btn-primary">保存</button>-->
<!--        	<button id="cancel"class="btn" onclick="location.href='/admin/ad/list/';return false;">取消</button>-->
<!--        </div>-->
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	        history.back();
	        }
	    }, 'json');
		return false;
	}});
});
</script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/front/js/jquery.datetimepicker.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/front/css/jquery.datetimepicker.css"/ >
<script>
$(function(){
    // 日期时间选择器
    $(".datetimepicker").datetimepicker({
        lang:"ch",
        i18n:{
        // 以中文显示月份
        de:{
            months:["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月",],
        // 以中文显示每周（必须按此顺序，否则日期出错）
            dayOfWeek:["日","一","二","三","四","五","六",]
            }
        },
        // 显示成年月日，时间--
        format:"Y-m-d H:i",
        // 限制不能选取今天之前
        minDate:0,
        //取消时间选择
        timepicker:true
    });
});
</script>