<div class="pheader clearfix">广告信息</div>
<div class="pbody clearfix">
	<form id="myform" class="form-horizontal" role="form" method="post" action="">
		<input name="iAutoID" type="hidden" value="<?php echo isset($aAd['iAdID'])?$aAd['iAdID']:''?>">
		<input name="iUserID" type="hidden" value="<?php echo isset($aAd['iUserID'])?$aAd['iUserID']:''?>">
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 用户名称：</label>
			<div class="col-sm-10">
			<?php echo $aUser['sRealName']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 广告名称：</label>
			<div class="col-sm-10">
			<?php echo isset($aAd['sAdName'])?$aAd['sAdName']:''?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 最小投放预算：</label>
			<div class="col-sm-10">
			<?php echo isset($aAd['iPlanMinMoney'])?$aAd['iPlanMinMoney']:''?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 最大投放预算：</label>
			<div class="col-sm-10">
			<?php echo isset($aAd['iPlanMaxMoney'])?$aAd['iPlanMaxMoney']:''?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 投放时间：</label>
			<div class="col-sm-10">
			<?php echo isset($aAd['iPlanTime'])?$aAd['iPlanTime']:''?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 媒体类型：</label>
			<div class="col-sm-10">
			<?php echo $iTypeName; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 广告类型：</label>
			<div class="col-sm-10">
		<?php echo $iAdType; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sTagID" class="col-sm-2 control-label"> 媒体分类：</label>
			<div class="col-sm-10">
    	   	<?php echo $aCat; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sTagID" class="col-sm-2 control-label"> 所在城市：</label>
			<div class="col-sm-10">
    	    <?php echo $aCityName; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 总价：</label>
			<div class="col-sm-10">
			<?php echo isset($aAd['iTotalMoney'])?$aAd['iTotalMoney']:''?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 支付类型：</label>
			<div class="col-sm-10">
			<?php echo (isset($aAd['iPayStatus'])&&$aAd['iPayStatus']=='0' ? '未付款' : '已付款'); ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<?php if($aAd['iMediaType'] == $type_weixin) { ?>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 广告位：</label>
			<div class="col-sm-10">
			<?php echo $aPos; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 显示时间：</label>
			<div class="col-sm-10">
			<?php echo date('Y-m-d H:i:s' , $rowAd['iShowTime']); ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 导入URL：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sImportUrl']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 上传Word：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sWordFile']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 标题：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sTitle']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 作者：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sAuthor']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 封面图片：</label>
			<div class="col-sm-10">
				<img
					src="<?php echo isset($rowAd['sCoverImg'])?Util_Uri::getDFSViewURL($rowAd['sCoverImg'], 130, 130):''?>"
					width="130" /> <span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 摘要：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sAbstract']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 内容：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sContent']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 原链接：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sOriginalUrl']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<?php } elseif ($aAd['iMediaType'] == $type_friend) { ?>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 投放形式：</label>
			<div class="col-sm-10">
			<?php echo $aPos; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发链接：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sForwardUrl']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发文字：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sForwardText']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发配图：</label>
			<div class="col-sm-10">
			<?php
			if ($rowAd['sForwardImg'] != '') {
				$arr = explode(',' , $rowAd['sForwardImg']);
				if (count($arr) > 0) {
					foreach ($arr as $v) {
						echo '<img src="'.Util_Uri::getDFSViewURL($v, 130, 130).'" width="130" />';
					} 
				}else{
					echo '<img src="'.Util_Uri::getDFSViewURL($rowAd['sOriginalUrl'], 130, 130).'" width="130" />';
				} 
			}
			?>
			<span class="validate_checktip"></span>
			</div>
		</div>	
		<?php } elseif ($aAd['iMediaType'] == $type_weibo) { ?>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 投放形式：</label>
			<div class="col-sm-10">
			<?php echo $aPos; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发链接：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sForwardUrl']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发文字：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sForwardText']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 转发配图：</label>
			<div class="col-sm-10">
			<?php
			if ($rowAd['sForwardImg'] != '') {
				$arr = explode(',' , $rowAd['sForwardImg']);
				if (count($arr) > 0) {
					foreach ($arr as $v) {
						echo '<img src="'.Util_Uri::getDFSViewURL($v, 130, 130).'" width="130" />';
					} 
				}else{
					echo '<img src="'.Util_Uri::getDFSViewURL($rowAd['sForwardImg'], 130, 130).'" width="130" />';
				} 
			}
			?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<?php } elseif ($aAd['iMediaType'] == $type_news) { ?>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 投放形式：</label>
			<div class="col-sm-10">
			<?php echo $aPos; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 标题：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sTitle']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 内容：</label>
			<div class="col-sm-10">
			<?php echo $rowAd['sContent']; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
		<?php } ?>
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"> 状态：</label>
			<div class="col-sm-10">
		<?php echo $iStatus; ?>
			<span class="validate_checktip"></span>
			</div>
		</div>
	    <div class="form-group">
			<label for="iMoney" class="col-sm-2 control-label"> 资源列表：</label>
			<div class="col-sm-10">
				<table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #000000;text-align:center;">
					<tr>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">#</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">用户名称</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">媒体名称</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">广告位</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">价格</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">执行时间</td>
						<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">支付状态</td>
						<td style="border-bottom: 1px solid #000000;">状态</td>
					</tr>
				<?php
					foreach ($aAdMedia as $keyAdMedia => $valAdMedia) {
						$iAutoID = $valAdMedia['iAutoID'];
						$sEmail = $valAdMedia['sEmail'];
						$sMediaName = $valAdMedia['sMediaName'];
						$iPosName = $valAdMedia['iPosName'];
						$iMoney = $valAdMedia['iMoney'];
						$iPlanTime = '';
						if ($valAdMedia['iPlanTime'] != '' && $valAdMedia['iPlanTime'] > 0){
							$iPlanTime = date('Y-m-d' , $valAdMedia['iPlanTime']);
						}
						$iPayStatusName = $valAdMedia['iPayStatusName'];
						$iStatusName = $valAdMedia['iStatusName'];
						echo <<<EOF
						<tr>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$iAutoID}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$sEmail}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$sMediaName}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$iPosName}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$iMoney}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$iPlanTime}</td>
							<td style="border-right: 1px solid #000000;border-bottom: 1px solid #000000;">{$iPayStatusName}</td>
							<td style="border-bottom: 1px solid #000000;">{$iStatusName}</td>
						</tr>
EOF;
					}
				?>
				</table>
			</div>
		</div>
	    <?php if(isset($aAd['iUpdateTime']) && $aAd['iUpdateTime'] > 0){ ?>
	    <div class="form-group">
				<label for="iMoney" class="col-sm-2 control-label"> 更新时间：</label>
				<div class="col-sm-10">
	    		<?php echo date('Y-m-d H:i:s' , $aAd['iUpdateTime']); ?>
	    	</div>
			</div>
	    <?php } ?>
		<div class="form-group">
			<label for="iMoney" class="col-sm-2 control-label"> 创建时间：</label>
			<div class="col-sm-10">
	   		<?php echo date('Y-m-d H:i:s' , $aAd['iCreateTime']); ?>
	   		</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="cancel"class="btn" onclick="location.href='/admin/ad/adexplode.html?id=<?php echo isset($aAd['iAdID'])?$aAd['iAdID']:''; ?>';return false;">导出</button>
        </div>
	</form>
</div>