<div class="pheader clearfix">网站内容列表</div>
<div class="pbody clearfix">
	<form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/website/list.html">
        <div class="row sousuo_now">
        	<div class="form-group">
                <label>上级标题：</label>
    		    <select name="iParentID" class="form-control">
    		        <option value="">选择</option>
    		        <?php foreach ($parentWebsite as $k => $v) {?>
    		        <option value="<?php echo $v['iWebSiteID']?>" <?php echo isset($aParam['iParentID'])&&$aParam['iParentID']==$v['iWebSiteID']?'selected':''?>><?php echo $v['sTitle']?></option>
    		    	<?php }?>
    		    </select>
        	</div>
        	<div class="form-group">
                <label>分类：</label>
    		    <select name="iType" class="form-control">
    		        <option value="">选择</option>
    		        <?php foreach ($iType as $k => $v) {?>
	    		    <option value="<?php echo $k?>" <?php echo isset($aParam['iType'])&&$aParam['iType']==$k?'selected':''?>><?php echo $v?></option>
	    		    <?php }?>
    		    </select>
        	</div>
            <div class="form-group">
                <label>标题：</label>
    		    <input type="text" value="<?php echo isset($aParam['sTitle']) ? $aParam['sTitle'] : '' ?>" class="form-control" name="sTitle" style="width: 200px">
        	</div>
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索">
            </div>
        </div>
    </form>
    <hr>
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="website_add">
    		<i class="icon-plus"></i> 增加网站内容
    	</button>
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center">上级标题</th>
    			<th class="text-center">页面</th>
    			<th class="text-center">标题</th>
    			<th class="text-center">更新时间</th>
    			<th class="text-center">创建时间</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $v) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $v['iWebSiteID']?></td>
    			<td class="text-center"><?php echo $v['sParentTitle']?></td>
    			<td class="text-center"><?php echo $v['sPage']?></td>
    			<td class="text-center"><?php echo $v['sTitle']?></td>
    			<td class="text-center"><?php echo ((isset($v['iUpdateTime']) && $v['iUpdateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iUpdateTime'])) : '');?></td>
    			<td class="text-center"><?php echo ((isset($v['iCreateTime']) && $v['iCreateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iCreateTime'])) : '');?></td>
    			<td class="text-center">
    			    <a href="/admin/website/edit?id=<?php echo $v['iWebSiteID']?>" title="编辑"><i class="icon-pencil icon-large"></i></a>
    			    <a class="website_delete" href="/admin/website/del?id=<?php echo $v['iWebSiteID']?>" role="button" data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>
<script>
$('.website_delete').click(function() {
	if (confirm("您确认要删除该网站内容吗？")) {
		$.get(this.href, function(ret){
			alert(ret.data);
		    if (ret.status) {
			    location.reload();
		    }
		}, 'json');
	}
	return false;
});
$('#website_add').click(function(){
	location.href = '/admin/website/add';
});
</script>