<div class="cf2 step_o">
	<div class="cf2 step_o_w">
		<ul class="step_o cf2 step_1">
			<li class="light">
				<span class="eng"></span>
				<p>添加推广</p>
			</li>
			<li>
				<span class="eng">2</span>
				<p>选择媒介</p>
			</li>
			<li>
				<span class="eng">3</span>
				<p>设置广告</p>
			</li>
			<li>
				<span class="eng">4</span>
				<p>支付款项</p>
			</li>
		</ul>
	</div>
	<!--end宽度-->
</div>
<!--end步骤-->

<div class="cf2 gray_border box_w">
	<dl class="gray_th">
		<dd>添加设置</dd>
	</dl>

	<form autocomplete="off">
	<table class="fill_table">
		<tr>
			<th width="120px">
				<span class="red_arrow">*</span>投放渠道：
			</th>
			<td>
				<ul class="input_list">
				    <?php foreach ($aType as $k => $v) {?>
				    <?php if (!empty($aAd) && $aAd['iMediaType']!=$k){continue;}?>
					<li>
						<label <?php if (empty($aAd)){?>onclick="location.href='/ad/add/type/<?php echo $k?>.html'"<?php }?>>
							<div class="sel_box sel_box_r">
								<input type="radio" id="mtype-<?php echo $k?>" value="<?php echo $k?>" name="iMediaType" <?php echo $iType==$k?'checked':''?> />
								<label for="mtype-<?php echo $k?>"></label>
							</div>
							<?php echo $v?>
						</label>
					</li>
					<?php }?>
				</ul>
			</td>
		</tr>
		<tr>
			<th>
				<span class="red_arrow">*</span>推广名称：
			</th>
			<td>
				<input type="text" placeholder="请输入推广名称" class="fill_text hover_input" name="sAdName" value="<?php echo empty($aAd)?'':$aAd['sAdName']?>">
				<label class="error sAdName" style="display: none"></label>
			</td>
		</tr>
		<tr>
			<th>
				投放预算：
			</th>
			<td>
				<input type="text" inputlimit="uint" class="fill_text hover_input" name="iPlanMinMoney" style="width: 80px; text-align: center;" value="<?php echo empty($aAd)?'':$aAd['iPlanMinMoney']?>"> 元
				<span class="p_t">-</span>
				<input type="text" inputlimit="uint" class="fill_text hover_input" name="iPlanMaxMoney" style="width: 80px; text-align: center;" value="<?php echo empty($aAd)?'':$aAd['iPlanMaxMoney']?>"> 元
				<label class="error iPlanMoney" style="display: none"></label>
			</td>
		</tr>
		<!-- 
		<tr>
        	<th>
        		<span class="red_arrow"></span>媒体类别：
        	</th>
        	<td>
        		<ul class="input_list" style="width: 740px;">
        		<?php foreach ($aData['aCategory'] as $k => $v) {?>
        			<li style="width:80px;margin-right:0px;overflow:hidden;">
        				<label>
        					<div class="sel_box sel_box_r">
        						<input type="radio" id="mtag-<?php echo $k?>" value="<?php echo $k?>" <?php echo !empty($aAd['aCatID'])&&in_array($k, $aAd['aCatID'])?'checked':''?> name="sCatID" />
        						<label for="mtag-<?php echo $k?>"></label>
        					</div>
        					<?php echo $v?>
        				</label>
        			</li>
        	    <?php }?>
        		</ul>
			    <samp class="more_btn" style="margin-top:10px;">更多</samp>
        		<label class="error aCatID" style="display: none;"></label>
        	</td>
        </tr>
         -->
		<tfoot>
			<tr>
				<td colspan="2">
					<input type="button" class="red_btn_t step_btn" value="下一步">
				</td>
			</tr>
		</tfoot>
	</table>
	</form>
</div>

<link href="<?php echo $sStaticRoot ?>/easyDialog/easydialog.css" rel="stylesheet" type="text/css">
<script src="<?php echo $sStaticRoot ?>/easyDialog/easydialog.min.js"></script>
<script type="text/javascript">
$(function() {
	$(".red_btn_t").click(function(){
		var form = $(this).parents('form').get(0);
	    $.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        if (ret.status) {
	            location.href = '/media/index/id/'+ret.data+'.html';
	        } else {
		        showErrorInfo(form, ret.data);
	        }
	    }, 'json');
		return false;
	});

	$('ul.input_list').each(function(){
    	$(this).find('li:gt(8)').hide();
    	if ($(this).find('li').length <= 8) {
        	$(this).next().hide();
    	}
    });
    $('.more_btn').click(function(){
    	var top_son_one = $(this).prev();
    	if(top_son_one.find('li:last').is(":visible")){
    		top_son_one.find('li:gt(8)').hide();
    		$(this).text("更多").removeClass('more_btn_light');
    	}else{
    		top_son_one.find('li').show();
    		$(this).text("收起").addClass('more_btn_light');
    	}
    });

    <?php if ($aUser['iFirst'] < 3) {?>
    $.get('/help/none/type/aprotocol.html', function(ret){
    	easyDialog.open({
            container : {
                header : '51wom服务条款',
                content : ret,
                yesFn : function(){
        			$.post('/user/first.html', {id:<?php echo $aUser['iUserID']?>});
        		},
                noFn : false
            }
        });
    }, 'text');
    <?php }?>
});
</script>