<div class="activate_w cf2">
	<dl class="activate_w">
		<dt>
			<img src="/front/images/tool/icon_succeed.png" class="png" alt="ok">
		</dt>
		<dd>
			<h4>恭喜，激活成功！</h4>
			<p>
				您已经成功的发布{xx}{xxx}，媒体编号：{id}<br>
				我们审核通过后，会尽快为您安排投放，请注意查看您的个人中心<a href="#">账号中心</a>
			</p>
			<div>
				<a href="/ad/add.html" class="red_btn_t">添加推广</a>
				<a href="/media/index.html" class="gray_btn">查看媒体</a>
			</div>
		</dd>
	</dl>
</div>