<div class="pheader clearfix">自媒体中心</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input type="hidden" name="iType" value="1">
		<div class="form-group">
			<label class="col-sm-1">所属分类</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="checkbox" name="aCatID" value="0"> 不限 
			    </label>
			    <?php foreach ($aType as $k => $v) {?>
			    <label class="form-inline">
			        <input type="checkbox" name="aCatID" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">推广价格</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="radio" name="iPrice" value="0"> 不限 
			    </label>
			    <?php foreach ($aPrice as $k => $v) {?>
			    <label class="form-inline">
			        <input type="radio" name="iPrice" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">粉丝数量</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="radio" name="iFollower" value="0"> 不限 
			    </label>
			    <?php foreach ($aFollower as $k => $v) {?>
			    <label class="form-inline">
			        <input type="radio" name="iFollower" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">所在城市</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="checkbox" name="iCityID" value="0"> 不限 
			    </label>
			    <?php foreach ($aCity as $k => $v) {?>
			    <label class="form-inline">
			        <input type="checkbox" name="iCityID" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">阅 读 量</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			            大于 <input type="text" name="iReadNum" value="0"> <input type="button" value="确定" id="iReadNum"> 
			    </label>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">推荐等级</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="radio" name="iLevel" value="0"> 不限 
			    </label>
			    <?php foreach ($aLevel as $k => $v) {?>
			    <label class="form-inline">
			        <input type="radio" name="iLevel" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">资源标签</label>
			<div class="col-sm-10">
			    <label class="form-inline">
			        <input type="checkbox" name="iLevel" value="0"> 不限 
			    </label>
			    <?php foreach ($aTag as $k => $v) {?>
			    <label class="form-inline">
			        <input type="checkbox" name="iLevel" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-1">已选规则</label>
			<div class="col-sm-10">
			    <?php foreach ($aParam as $k => $v) {?>
			    <label class="form-inline">
			        <input type="radio" name="iLevel" value="<?php echo $k?>" <?php echo $k == 1?'checked':''?>> <?php echo $v?>
			    </label>
			    <?php }?>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
global.sUploadUrl = '<?php echo Util_Common::getConf('upload', 'url')?>';
global.sDfsViewUrl = '<?php echo Util_Common::getConf('dfsview', 'url')?>';
</script>

<link href="<?php echo $sStaticRoot ?>/webuploader/webuploader.css" rel="stylesheet" type="text/css">
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/webuploader/webuploader.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/webuploader.js"></script>

<script type="text/javascript">
$(function() {
	$("#savebtn").click(function(){
		var form = $('#myform');
	    $.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            //location.href = '/admin/city/list/';
	        }
	    }, 'json');
		return false;
	});
});
</script>