<div class="activate_w cf2">
	<dl class="activate_w">
		<dt>
			<img src="/front/images/tool/icon_succeed.png" class="png" alt="ok">
		</dt>
		<dd>
			<h4>恭喜，提现申请成功！</h4>
			<p>
				我们将在7个工作日内为您安排付款，请耐心等待。<br>
				如有疑问，可拨打电话 <font color="blue">400-8789551</font>
				<br><br>
				您还可以：
			</p>
			<div>
				<a href="/mcenter/cashout.html" class="red_btn_t">再次提现</a>
				<a href="/mcenter/index.html" class="gray_btn">返回首页</a>
			</div>
		</dd>
	</dl>
</div>