<?php $iTopNav=1; include 'topnav.phtml';?>
<?php ?>
<dl class="tab_nav_text">
	<dd>
		<a href="/mcenter/index/type/12.html" class="minitip <?php echo $iType==12?'tab_light':''?>" title="等待媒体主全部订单">全部订单 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>
		<a href="/mcenter/index/type/2.html" class="minitip <?php echo $iType==2?'tab_light':''?>" title="等待媒体主处理的订单">待接单 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>    		
        <a href="/mcenter/index/type/3.html" class="minitip <?php echo $iType==3?'tab_light':''?>" title="等待媒体主提交预览的订单">待提交预览 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>
        <a href="/mcenter/index/type/4.html" class="minitip <?php echo $iType==4?'tab_light':''?>" title="等待广告主对提交预览内容进行确认的订单">待内容确认 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>    		
        <a href="/mcenter/index/type/5.html" class="minitip <?php echo $iType==5?'tab_light':''?>" title="等待媒体主对广告进行投放的订单">待投放 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>    		
        <a href="/mcenter/index/type/6.html" class="minitip <?php echo $iType==6?'tab_light':''?>" title="等待媒体主提交广告效果截图的订单">待提交效果 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>    		
        <a href="/mcenter/index/type/7.html" class="minitip <?php echo $iType==7?'tab_light':''?>" title="等待广告主确认广告效果的订单">待确认效果 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>
        <a href="/mcenter/index/type/8.html" class="minitip <?php echo $iType==8?'tab_light':''?>" title="已经结算完成的订单">已完成 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a><em class="china">|</em>    		
        <a href="/mcenter/index/type/11.html" class="minitip <?php echo $iType==11?'tab_light':''?>" title="媒体主拒绝了的订单">已拒单 <img style="margin-top:5px;" src="/front/images/tool/icon_what.png" width="10" height="10"></a>      
	</dd>
</dl>
<div class="tab_box tab_box_o" style="margin-bottom:20px">
	<div>
		<table class="list_table">
			<thead>
				<tr>
					<th>订单号</th>
					<th>推广名称</th>
					<th>媒体类型</th>
					<th>执行帐号</th>
					<th>任务时间</th>
					<th>推广金额</th>
					<th>订单状态</th>
					<th>处理</th>
				</tr>
			</thead>
			<tbody>
			<?php if (empty($aData['aList'])) {?>
			    <tr>
			        <td colspan="9">无内容</td>
			    </tr>
			<?php } else {?>
			<?php foreach ($aData['aList'] as $k => $v) {?>
				<tr>
					<td>
						<!--<span class="blue_link"><a href="/mcenter/daxq?id=<?php echo $v['iAutoID']?>"><?php echo $v['iAutoID']?></a></span>-->
						<span class="eng"><?php echo $v['iAutoID']?></span>
					</td>
					<td>
						<a target="_blank" class="pinka" href="/index/index/ad/id/<?php echo $v['iAdID']?>/type/2.html"><?php echo $v['aAd']['sAdName']?></a>
					</td>
					<td>
						<span class="eng"><?php echo $aType[$v['aMedia']['iMediaType']]?></span>
					</td>
					<td>
						<span class="eng"><?php echo $v['aAd']['sAdName']?></span>
					</td>
					<td>
						<span class="eng"><?php echo date('Y-m-d H:i', $v['iPlanTime'])?></span>
					</td>
					<td>
						<span class="red_text eng">&yen;<?php echo $v['iMoney']?></span>
					</td>
					<td>
						<?php if ($aStatus[$v['iStatus']]=='待接单'&& intval($v['iPlanTime'])+7200<=time())
						{
							Model_AdMedia::query("UPDATE t_ad_media SET iStatus=11 WHERE iAutoID={$v['iAutoID']}");
							?>
							<span class="eng"><?php echo $aStatus[$v['iStatus']]?></span>
						<?php } else {?>
							<span class="eng"><?php echo $aStatus[$v['iStatus']]?></span>
						<?php } ?>
					</td>
					<td>
					    <?php if ($v['iStatus'] == Model_AdMedia::STATUS_RECEIVE) {?>
					    <a class="orderdone olda" data-tips="你确认要接此订单吗?" href="/mcenter/done/id/<?php echo $v['iAutoID']?>/status/1.html">接单</a> |
					    <a class="orderdone olda" data-tips="你确认不接此订单吗?" href="/mcenter/done/id/<?php echo $v['iAutoID']?>/status/0.html">拒单</a>
					    <?php } elseif ($v['iStatus'] == Model_AdMedia::STATUS_SUBMIT_PREVIEW) {?>
					    <a class="olda" href="/mcenter/preview/id/<?php echo $v['iAutoID']?>.html">提交预览</a>
					    <?php } elseif ($v['iStatus'] == Model_AdMedia::STATUS_PUSH) {?>
					    <a class="olda" data-tips="你确认已经投放广告了吗?" href="/mcenter/online/id/<?php echo $v['iAutoID']?>.html">投放</a>
					    <?php } elseif ($v['iStatus'] == Model_AdMedia::STATUS_CONFIRM_EFFECT) {?>
					    <a target="_blank" class="olda" href="<?php echo Util_Uri::getDFSViewURL($v['sEffectImg'])?>">效果</a>
					    <?php } elseif ($v['iStatus'] == Model_AdMedia::STATUS_SUBMIT_EFFECT) {?>
					    <a class="olda" href="/mcenter/effect/id/<?php echo $v['iAutoID']?>.html">提交效果</a>
					    <?php } else {?>
					    -
					    <?php }?>
					</td>
				</tr>
				<?php }?>
			<?php }?>
			</tbody>
		</table>
		
		<div class="pager">
		<?php echo $aData['aPager']?>
		</div>
	</div>
</div>
<script>
$(function(){
	$('.orderdone').click(function(){
		if (confirm($(this).data('tips'))) {
			$.post(this.href, {}, function(ret){
    			if (ret.status) {
    				alert(ret.data);
    				location.reload();
    			} else {
    				alert(ret.data);
    			}
    	    });
		}
		return false;
	});
});
</script>