<ul class="cf2 sec_nav">
	<li class="cf2">
		<a class="round_s <?php echo $iTopNav==1?'light':''?>" href="/mcenter/index/type/1.html"> <span class="png n_1"></span>订单中心</a>
		<a class="round_s <?php echo $iTopNav==2?'light':''?>" href="/mcenter/account/type/1.html"> <span class="png n_2"></span>帐号中心</a>
		<a class="round_s <?php echo $iTopNav==3?'light':''?>" href="/mcenter/finance.html"> <span class="png n_3"></span>财务中心</a>
		<a class="round_s <?php echo $iTopNav==4?'light':''?>" href="/mcenter/coinfo.html"> <span class="png n_4"></span>个人信息</a>

	</li>
</ul>