<div class="cf2 step_o">
	<div class="cf2 step_o_w">
		<ul class="step_o cf2 step_m step2_1">
			<li>
				<span class="eng"></span>
				<p>添加媒体</p>
			</li>
			<li>
				<span class="eng">2</span>
				<p>填写报价</p>
			</li>
			<li>
				<span class="eng">3</span>
				<p>等待接单</p>
			</li>
		</ul>
	</div>
	<!--end宽度-->
</div>
<!--end步骤-->

<div class="cf2 box_w gray_border">
	<dl class="gray_th">
		<dd>创建帐号</dd>
	</dl>
<form autocomplete="off">
    <input type="hidden" name="iMediaID" value="<?php echo $aMedia['iMediaID']?>">
	<table class="fill_table">
		<tr>
			<th width="120px">
				<span class="red_arrow">*</span>媒体类型：
			</th>
			<td>
				<ul class="input_list">
				    <?php foreach ($aType as $k => $v) {?>
				    <?php if (!empty($aMedia) && $aMedia['iMediaType']!=$k){continue;}?>
					<li>
						<label <?php if (empty($aMedia)){?>onclick="location.href='/media/add/type/<?php echo $k?>.html'"<?php }?>>
							<div class="sel_box sel_box_r">
								<input type="radio" id="mtype-<?php echo $k?>" value="<?php echo $k?>" name="iMediaType" <?php echo $iType==$k?'checked':''?> />
								<label for="mtype-<?php echo $k?>"></label>
							</div>
							<?php echo $v?>
						</label>
					</li>
					<?php }?>
				</ul>
			</td>
		</tr>
		<?php include 'add_' . $iType . '.phtml';?>
		<!-- 
        <tr>
        	<th>
        		<span class="red_arrow">*</span>媒体类别：
        	</th>
        	<td>
        		<ul class="input_list">
        		<?php foreach ($aData['aCategory'] as $k => $v) {?>
        			<li style="width:90px;margin-right:0px">
        				<label>
        					<div class="sel_box sel_box_r">
        						<input type="radio" id="mtag-<?php echo $k?>" value="<?php echo $k?>" <?php echo !empty($aMedia['aCatID'])&&in_array($k, $aMedia['aCatID'])?'checked':''?> name="aCatID[]" />
        						<label for="mtag-<?php echo $k?>"></label>
        					</div>
        					<?php echo $v?>
        				</label>
        			</li>
        	    <?php }?>
        		</ul>
        		<label class="error aCatID" style="display: none;"></label>
        	</td>
        </tr>
        -->
        <tr>
			<th>
				<span class="red_arrow">*</span>媒体标签：
			</th>
			<td>
				<ul class="input_list" id="category">
				<?php foreach ($aData['aTag'] as $k => $v) {?>
					<li style="width:90px;margin-right:0px">
						<label>
							<div class="sel_box">
								<input type="checkbox" id="mtag-<?php echo $k?>" value="<?php echo $k?>" <?php echo !empty($aMedia['aTagID'])&&in_array($k, $aMedia['aTagID'])?'checked':''?> name="aTagID[]" />
								<label for="mtag-<?php echo $k?>"></label>
							</div>
							<?php echo $v?>
						</label>
					</li>
			    <?php }?>
				</ul>
				<label class="error aTagID" style="display: none;"></label>
			</td>
		</tr>
		<tr>
			<th>
				<span class="red_arrow">*</span>所在城市：
			</th>
			<td>
				<ul class="input_list" id="mcity">
				<?php foreach ($aData['aCity'] as $k => $v) {?>
					<li style="width:90px;margin-right:0px">
						<label>
							<div class="sel_box">
								<input type="checkbox" id="mcity-<?php echo $k?>" value="<?php echo $k?>" <?php echo !empty($aMedia['aCityID'])&&in_array($k, $aMedia['aCityID'])?'checked':''?> name="aCityID[]" />
								<label for="mcity-<?php echo $k?>"></label>
							</div>
							<?php echo $v?>
						</label>
					</li>
			    <?php }?>
				</ul>
				<label class="error aCityID" style="display: none"></label>
			</td>
		</tr>
		<tfoot>
			<tr>
				<td colspan="2">
					<input type="button" class="red_btn_t step_btn" value="下一步">
				</td>
			</tr>
		</tfoot>
	</table>
</form>
</div>
<!--end中间区域-->
<script type="text/javascript">
global.sUploadUrl = '<?php echo Util_Common::getConf('upload', 'url')?>';
global.sDfsViewUrl = '<?php echo Util_Common::getConf('dfsview', 'url')?>';
</script>
<link href="<?php echo $sStaticRoot ?>/easyDialog/easydialog.css" rel="stylesheet" type="text/css">
<script src="<?php echo $sStaticRoot ?>/easyDialog/easydialog.min.js"></script>
<link href="<?php echo $sStaticRoot ?>/webuploader/webuploader.css" rel="stylesheet" type="text/css">
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/webuploader/webuploader.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/webuploader.js"></script>

<script type="text/javascript">
$(function() {
	$('#sMediaName, #sOpenName').blur(function(){
		var eid = this.id;
		if (this.value.length < 2) {
			$('label.' + eid).html($(this).attr('placeholder')).show();
			return false;
		}
		$.get('/media/check/type/<?php echo $iType?>/field/'+this.id+'/value/' + this.value, function(ret){
			if (ret.status) {
				$('label.' + eid).hide();
			} else {
			    $('label.' + eid).html(ret.data).show();
			}
		});
	});
	$('#category :checkbox').click(function(){
		if ($('#category :checkbox:checked').length > 6) {
			alert('媒体标签最多只能选择6个');
			$('label.aTagID').html('媒体标签最多只能选择6个').show();
			return false;
		} else {
			$('label.aTagID').hide();
		}
	});
	$('#mcity :checkbox').click(function(){
		if ($('#mcity :checkbox:checked').length > 3) {
			alert('所在城市最多只能选择3个');
			$('label.aCityID').html('所在城市最多只能选择3个').show();
			return false;
		} else {
			$('label.aCityID').hide();
		}
	});
	
	$(".red_btn_t").click(function(){
		var form = $(this).parents('form').get(0);
	    $.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        if (ret.status) {
	            location.href = '/media/add2/id/'+ret.data+'.html';
	        } else {
		        showErrorInfo(form, ret.data);
	        }
	    }, 'json');
		return false;
	});

	<?php if ($aUser['iFirst'] < 3) {?>
	$.get('/help/none/type/mprotocol.html', function(ret){
    	easyDialog.open({
            container : {
                header : '51wom服务条款',
                content : ret,
                yesFn : function(){
        			$.post('/user/first.html', {id:<?php echo $aUser['iUserID']?>});
        		},
                noFn : false
            }
        });
    }, 'text');
    <?php }?>
});
</script>