	<!--	<dt class="cf2">
			<div class="l">
				推荐等级<a href="javascript:;" class="help_a"><img class="minitip" title="推荐等级由系统加权计算，值越高越值得关注"
					src="/front/images/tool/icon_what.png" alt="" width="18"
					height="18"></a>
			</div>
			<em class="r"> 
			    <a style="width:75px;margin-right:0px" href="<?php echo Util_Uri::makeSearchUrl($aParam, 'score', null)?>" <?php echo empty($aParam['score'])?'class="light"':''?>><b>不限</b></a>
			    <a href="<?php echo Util_Uri::makeSearchUrl($aParam, 'score', '90', 0)?>" <?php echo !empty($aParam['score']) && $aParam['score']==90?'class="light"':''?>><b>强烈推荐(90分以上)</b></a>
				<a href="<?php echo Util_Uri::makeSearchUrl($aParam, 'score', '80', 0)?>" <?php echo !empty($aParam['score']) && $aParam['score']==80?'class="light"':''?>><b>非常推荐(80分以上)</b></a>
				<a href="<?php echo Util_Uri::makeSearchUrl($aParam, 'score', '70', 0)?>" <?php echo !empty($aParam['score']) && $aParam['score']==70?'class="light"':''?>><b>推荐(70分以上)</b></a>
				<a href="<?php echo Util_Uri::makeSearchUrl($aParam, 'score', '1', 0)?>" <?php echo !empty($aParam['score']) && $aParam['score']==1?'class="light"':''?>><b>普通(70分以下)</b></a>
			</em>
		</dt>
        
		
		<dt class="cf2">
        <div class="winth-w">
			<div class="l">阅读量<a href="javascript:;" class="help_a"><img class="minitip" title="输入自媒体阅读量"
					src="/front/images/tool/icon_what.png" alt="" width="18"
					height="18"></a></div>
			<em class="r"> 
			    <span style="padding-left: .8em;">
			         <input type="text" inputlimit="uint" class="fill_text fill_text_s hover_input" id="readnum0" value="<?php echo isset($aParam['readnum0'])?$aParam['readnum0']:''?>" placeholder="输入数量">
			         ~
			         <input type="text" inputlimit="uint" class="fill_text fill_text_s hover_input" id="readnum1" value="<?php echo isset($aParam['readnum1'])?$aParam['readnum1']:''?>" placeholder="输入数量"> 
			    <input type="button" class="gray_btn gray_btn_s" value="确定" onclick="location.href='<?php echo Util_Uri::makeSearchUrl($aParam, array('readnum0','readnum1'), array(null,null))?>?readnum0='+$('#readnum0').val()+'&readnum1='+$('#readnum1').val()"></span>
			</em>
            </div>
	</dt> -->