<div class="pheader clearfix"><?php echo isset($aProxy['iProxyID'])?'编辑':'增加'?>代理</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iProxyID" type="hidden" value="<?php echo isset($aProxy['iProxyID'])?$aProxy['iProxyID']:''?>">
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"><strong style="color:red;">*</strong> Proxy地址：</label>
			<div class="col-sm-10">
				<input name="sProxy" type="text" validate="!length:1-50" value="<?php echo isset($aProxy['sProxy'])?$aProxy['sProxy']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
    	<div class="form-group">
    		<label for="iStatus" class="col-sm-2 control-label"> 状态：</label>
    		<div class="col-sm-10">
    			<select name="iStatus" class="form-control" style="width:250px;">
    				<option value="1" <?php echo isset($aProxy['iStatus'])&&$aProxy['iStatus']=='1'?'selected':''?>>有效</option>
    		        <option value="0" <?php echo isset($aProxy['iStatus'])&&$aProxy['iStatus']=='0'?'selected':''?>>无效</option>
    		    </select>
    		</div>
    	</div>
		<div class="form-group">
			<label for="iFailNum" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 下载失败次数：</label>
			<div class="col-sm-10">
			    <input name="iFailNum" validate="!float:true" type="text" value="<?php echo isset($aProxy['iFailNum'])?$aProxy['iFailNum']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="iBanNum" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 屏蔽次数：</label>
			<div class="col-sm-10">
			    <input name="iBanNum" validate="!float:true" type="text" value="<?php echo isset($aProxy['iBanNum'])?$aProxy['iBanNum']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php if(isset($aProxy['iProxyID'])){ ?>
    	<?php if(isset($aProxy['iUpdateTime']) && $aProxy['iUpdateTime'] > 0){ ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 更新时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aProxy['iUpdateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 创建时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aProxy['iCreateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 修改密码：</label>
			<div class="col-sm-10">
			    <input name="pwd" validate="!length:2-50" type="password" value="" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/crawlproxy/list/';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/admin/crawlproxy/list/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>