<div class="pheader clearfix">代理列表</div>
<div class="pbody clearfix">
	<form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/crawlproxy/list.html">
        <div class="row sousuo_now">
            <div class="form-group">
                <label>Proxy地址：</label>
    		    <input type="text" value="<?php echo isset($aParam['sProxy']) ? $aParam['sProxy'] : '' ?>" class="form-control" name="sProxy" style="width: 200px">
        	</div>
        	<div class="form-group">
                <label>状态：</label>
    		    <select name="iStatus" class="form-control" style="width:250px;">
    		    	<option value="" <?php echo isset($aParam['iStatus'])&&$aParam['iStatus']==''?'selected':''?>>全部</option>
    				<option value="1" <?php echo isset($aParam['iStatus'])&&$aParam['iStatus']=='1'?'selected':''?>>有效</option>
    		        <option value="0" <?php echo isset($aParam['iStatus'])&&$aParam['iStatus']=='0'?'selected':''?>>无效</option>
    		    </select>
        	</div>
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索">
            </div>
        </div>
    </form>
    <hr>
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="crawlproxy_add">
    		<i class="icon-plus"></i> 增加代理
    	</button>
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center">Proxy地址</th>
    			<th class="text-center">状态</th>
    			<th class="text-center">下载失败次数</th>
    			<th class="text-center">屏蔽次数</th>
    			<th class="text-center">更新时间</th>
    			<th class="text-center">创建时间</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $v) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $v['iProxyID']?></td>
    			<td class="text-center"><?php echo $v['sProxy']?></td>
    			<td class="text-center"><?php echo ((isset($v['iStatus']) && $v['iStatus'] == 1) ? '有效' : '无效');?></td>
    			<td class="text-center"><?php echo $v['iFailNum'];?></td>
    			<td class="text-center"><?php echo $v['iBanNum'];?></td>
    			<td class="text-center"><?php echo ((isset($v['iUpdateTime']) && $v['iUpdateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iUpdateTime'])) : '');?></td>
    			<td class="text-center"><?php echo ((isset($v['iCreateTime']) && $v['iCreateTime'] > 0) ? (date('Y-m-d H:i:s' , $v['iCreateTime'])) : '');?></td>
    			<td class="text-center">
    			    <a href="/admin/crawlproxy/edit?id=<?php echo $v['iProxyID']?>" title="编辑"><i class="icon-pencil icon-large"></i></a>
    			    <a class="crawlproxy_delete" href="/admin/crawlproxy/del?id=<?php echo $v['iProxyID']?>" role="button" data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>

<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/xcConfirm.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/js/xcConfirm.css"/>
<style type="text/css">
.sgBtn{width: 135px; height: 35px; line-height: 35px; margin-left: 10px; margin-top: 10px; text-align: center; background-color: #0095D9; color: #FFFFFF; float: left; border-radius: 5px;}
</style>
<script>
$('.crawlproxy_delete').click(function() {
	var url = this.href;
	if (confirm("您确认要删除该代理信息吗？")) {
		var txt=  "请输入密码：";
		window.wxc.xcConfirm(txt, window.wxc.xcConfirm.typeEnum.input,{
			onOk:function(v){
				if (v.trim() != '') {
					$.post('/admin/user/seditpwd', {'pwd':v.trim()}, function(ret){
						if (ret.status) {
							$.get(url, function(ret){
								alert(ret.data);
								if (ret.status) {
									location.reload();
								}
							}, 'json');
						}
						else {
							alert(ret.data);
						}
					}, 'json');
				}
				else {
					alert('修改密码不可以为空');
					//return false;
				}
			}
		});
	}
	return false;
});
$('.crawlproxy_delete').click(function() {
	if (confirm("您确认要删除该敏感词吗？")) {
		$.get(this.href, function(ret){
			alert(ret.data);
		    if (ret.status) {
			    location.reload();
		    }
		}, 'json');
	}
	return false;
});
$('#crawlproxy_add').click(function(){
	location.href = '/admin/crawlproxy/add';
});
</script>