<?php $iTopNav=3; include 'topnav.phtml';?>

<dl class="tab_nav_text">
	<dd style="float:left">
		<a href="/acenter/finance.html" class="tab_light">账单明细</a><em class="china">|</em>
		<a href="/acenter/cashin.html">立即充值</a><em class="china">|</em>
        <a href="/acenter/cashout.html">立即提现</a>
	</dd>
	<dt style="float:right">
	    可提现余额为：<b class="eng red_text">&yen;<?php echo $aUser['iMoney']?></b>
	</dt>
</dl>

<div class="tab_box tab_box_o">
	<div>
		<table class="list_table">
			<thead>
				<tr>
					<th>流水号</th>
					<th>时间</th>
					<th>分类</th>
					<th>金额</th>
					<th>当前余额</th>
					<th>账单明细</th>
					<th>备注</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($aData['aList'] as $k => $v) {?>
				<tr>
					<td><span class="eng"><?php echo $v['iAutoID']?></span></td>
					<td><span class="eng"><?php echo date('Y-m-d H:i:s', $v['iCreateTime'])?></span></td>
					<td><span class="blue_link"><?php echo $aPayment[$v['iPayment']]?></span></td>
					<td><span class="red_text eng">&yen;<?php echo $v['iPayMoney']?></span></td>
					<td><span class="eng">&yen;<?php echo $v['iUserMoney']?></span></td>
					<td><?php echo $aSource[$v['iSource']]?></td>
					<td><?php echo $v['sRemark']?></td>
				</tr>
		    <?php }?>
			</tbody>
		</table>
		<div class="pager">
		<?php echo $aData['aPager']?>
		</div>
	</div>
</div>

<dl class="cf2 w_1000 d_money">
	<dt>
		可提现余额为：<b class="eng red_text">&yen;<?php echo $aUser['iMoney']?></b>
	</dt>
	<dd>
		<a href="/acenter/cashout.html" class="red_btn_t">提现</a>
		<a style="margin-left: 20px;" class="olda" href="/acenter/export.html">导出账单明细</a>
	</dd>
</dl>